In [84]:
import numpy as np
A = np.random.randn(3,4)
print 'The created matrix is :\n', A
print '\n The matrix after slicing the first two columns are : \n', A[:,2:]

The created matrix is :
[[-0.39724661  0.32639271 -1.06509816 -0.61539139]
 [-0.3630326  -0.12187476 -1.23970206 -0.60617232]
 [ 0.14153291 -1.50000213  0.58969614 -0.30868113]]

 The matrix after slicing the first two columns are : 
[[-1.06509816 -0.61539139]
 [-1.23970206 -0.60617232]
 [ 0.58969614 -0.30868113]]


In [85]:
B = A[:,0:2]
B

array([[-0.39724661,  0.32639271],
       [-0.3630326 , -0.12187476],
       [ 0.14153291, -1.50000213]])

In [86]:
np.where(B>0,0,B)

array([[-0.39724661,  0.        ],
       [-0.3630326 , -0.12187476],
       [ 0.        , -1.50000213]])

In [87]:
import pandas as pd
S = pd.Series([1,2,-3,4], index =['a','b','c','d'])
S

a    1
b    2
c   -3
d    4
dtype: int64

In [88]:
S = np.abs(S)
S

a    1
b    2
c    3
d    4
dtype: int64

In [89]:
ball_frame = pd.read_csv('https://raw.githubusercontent.com/jokecamp/FootballData/master/UEFA_European_Championship/Euro%202012/Euro%202012%20stats%20TEAM.csv', sep = ',')
ball_frame.head(8)

Team  Goals  Shots on target  Shots off target Shooting Accuracy  \
0         Croatia      4               13                12             51.9%   
1  Czech Republic      4               13                18             41.9%   
2         Denmark      4               10                10             50.0%   
3         England      5               11                18             50.0%   
4          France      3               22                24             37.9%   
5         Germany     10               32                32             47.8%   
6          Greece      5                8                18             30.7%   
7           Italy      6               34                45             43.0%   

  % Goals-to-shots  Total shots (inc. Blocked)  Hit Woodwork  Penalty goals  \
0            16.0%                          32             0              0   
1            12.9%                          39             0              0   
2            20.0%                          27             1              0   
3            17.2%                          40             0              0   
4             6.5%                          65             1              0   
5            15.6%                          80             2              1   
6            19.2%                          32             1              1   
7             7.5%                         110             2              0   

   Penalties not scored      ...       Saves made  Saves-to-shots ratio  \
0                     0      ...               13                 81.3%   
1                     0      ...                9                 60.1%   
2                     0      ...               10                 66.7%   
3                     0      ...               22                 88.1%   
4                     0      ...                6                 54.6%   
5                     0      ...               10                 62.6%   
6                     1      ...               13                 65.1%   
7                     0      ...               20                 74.1%   

   Fouls Won Fouls Conceded  Offsides  Yellow Cards  Red Cards  Subs on  \
0         41             62         2             9          0        9   
1         53             73         8             7          0       11   
2         25             38         8             4          0        7   
3         43             45         6             5          0       11   
4         36             51         5             6          0       11   
5         63             49        12             4          0       15   
6         67             48        12             9          1       12   
7        101             89        16            16          0       18   

   Subs off  Players Used  
0         9            16  
1        11            19  
2         7            15  
3        11            16  
4        11            19  
5        15            17  
6        12            20  
7        18            19  

[8 rows x 35 columns]

In [90]:
len(ball_frame)

16

In [91]:
ball_frame.isnull().sum() 


Team                          0
Goals                         0
Shots on target               0
Shots off target              0
Shooting Accuracy             0
% Goals-to-shots              0
Total shots (inc. Blocked)    0
Hit Woodwork                  0
Penalty goals                 0
Penalties not scored          0
Headed goals                  0
Passes                        0
Passes completed              0
Passing Accuracy              0
Touches                       0
Crosses                       0
Dribbles                      0
Corners Taken                 0
Tackles                       0
Clearances                    0
Interceptions                 0
Clearances off line           1
Clean Sheets                  0
Blocks                        0
Goals conceded                0
Saves made                    0
Saves-to-shots ratio          0
Fouls Won                     0
Fouls Conceded                0
Offsides                      0
Yellow Cards                  0
Red Card

In [83]:
ball_frame['Clearances off line'].fillna(0.0, inplace = True)
ball_frame['Clearances off line']

0     0.0
1     2.0
2     0.0
3     1.0
4     0.0
5     0.0
6     0.0
7     1.0
8     0.0
9     0.0
10    0.0
11    1.0
12    0.0
13    0.0
14    0.0
15    0.0
Name: Clearances off line, dtype: float64

In [82]:
Frame3 = ball_frame.sort_values(by = 'Shots on target', ascending = False)
Frame3.head(1)

Team  Goals  Shots on target  Shots off target Shooting Accuracy  \
13  Spain     12               42                33             55.9%   

   % Goals-to-shots  Total shots (inc. Blocked)  Hit Woodwork  Penalty goals  \
13            16.0%                         100             0              1   

    Penalties not scored      ...       Saves made  Saves-to-shots ratio  \
13                     0      ...               15                 93.8%   

    Fouls Won Fouls Conceded  Offsides  Yellow Cards  Red Cards  Subs on  \
13        102             83        19            11          0       17   

    Subs off  Players Used  
13        17            18  

[1 rows x 35 columns]