# numpy array or N-dimentional array

In [0]:
import sys
!{sys.executable} -m pip install numpy



You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/bin/sh: /Users/antonypaulson/anaconda3/envs/py27/bin/python-m: No such file or directory


In [0]:
import sys
!{sys.executable}-m pip install pandas

/bin/sh: /Users/antonypaulson/anaconda3/envs/py27/bin/python-m: No such file or directory


In [1]:
import math
a = 5
b = 2
c = float(a/b)
print c

2.0


In [2]:
#if you were to print them, there is a small difference.Actualy they are completely two different thing.  
print a, A

5

NameError: ignored

In [0]:
import numpy as np
a=[[1,2,3,4,5],[6,7,8,9,10]]
A=np.array(a)# create a np array. A is also a 2 by 5 matrix
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [0]:
print A

In [0]:
A.dtype

dtype('int64')

In [0]:
np.arange(0,10,2) #it returns a np array starting from 0 to 10, but not including 10. The increment is 2 each time. 

# Shape

In [0]:
#shape is an attribute of np array. It shows the shape of the matrix. 
A.shape

In [0]:
B=np.array([1, 2, 3, 4, 5])
B.shape
# why it's not 1 by 5 matrix, or (1,5)? Because [1, 2, 3, 4, 5] shows 5 elements in square bracket, or 5 rows. 

(5,)

In [0]:
#How do we make B an 5 by 1 matrix?
#reshape function returns to a multi-dim matrix. 
B=np.array([1, 2, 3, 4, 5])
B.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [0]:
# pay attention that shape and reshape funciton only applys to ndarray. 
C =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
C.reshape(3,3)

In [0]:
C.shape # if you want to change C to 3 by 3 matrix, then you need to assign the reshape return to C. 

In [0]:
C =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
C =C.reshape(3,3)
C

# More functions

In [0]:
np.zeros((4,3)) # np.zeros((n,m)) returns to an n by m matrix that contians zeros. 

In [0]:
np.zeros(8)

In [0]:
np.ones((2,2))

In [4]:
import numpy as np
A=np.array([[1,2],[3,4]])
np.empty(A)

TypeError: ignored

In [0]:
np.eye(6) # eye stands for Identity and sysmetric. This function retruns to an edentity matrix with specific dimentions. 

# Numeircal Operations on Matrices

In [0]:
#np.dot() multiply tow matrices. 

#generate an identity matrix of (3 x 3)
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
# generate another (3 x 3) matrix to be multiplied.
D = np.arange(1,10).reshape(3,3) # no stepsize is specified means stepsize is 1. 
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
M = np.dot(D,I)
M

In [0]:
# sum along each raw M
N=np.sum(M, axis=1)
N

In [0]:
# sum along each column of M
N=np.sum(M, axis=0)
N

In [0]:
I*10

In [0]:
I+D

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [0]:
1/D

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
1/D.astype(np.float64)

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

# Data Types for Numpy Arrays

the type name, like float or int, followed by a number indicating the number of bits per element. 

In [0]:
A=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.float64)
A

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [0]:
B=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.int64)
B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [0]:
#or you can use astype method. In this example, integers were cast to float. 
A=np.array([[1,2,3,4,5],[6,7,8,9,10]]) # by defining this, type of A will be int64. 
B=A.astype(np.float64)
B

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [0]:
#In this example, floating numbers are cast to integer type int32. The decimal part will be truncated. 
A=np.array([[1.5, 2.3],[3.4,1.9]])
B=A.astype(np.int32)
B

array([[1, 2],
       [3, 1]], dtype=int32)

In [0]:
# Or you can convert strings numbers to float. 
A=np.array([['1.5', '2.3'],['3.4','1.9']])
B=A.astype(np.float64)
B.dtype

dtype('float64')

# Indexing and Slicing

In [0]:
a=np.arange(10) # create a one-dimentional array. 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[5] #index 5 means 6th element. 

5

In [0]:
a[0:3]#return to a np array from first to third elements, or elements with index 0-2. 

array([0, 1, 2])

In [0]:
a[0:3]=10
a

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9])

In [0]:
#make a[0:3] a new np array, call it a_slice. 
a_slice=a[0:3]
a_slice[2]=1000
a
#changes on the a_slice will also be reflected in the original array. 

array([  10,   10, 1000,    3,    4,    5,    6,    7,    8,    9])

In [0]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A[2]

array([7, 8, 9])

In [0]:
A[0][0] #A[row index] [column index]. In textbook, row is called axis 0, and column is called axis 1. 

1

In [0]:
A[0,0]

1

In [0]:
#slicing a two dimentional array
A[:2] #return to first a np array containing firs two rows, row 0 and row 1. 


array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
A[:2,1:]# it returns to row 0, row 1 and column 1 and column 2. 

array([[2, 3],
       [5, 6]])

In [0]:
A[:,:2]# note that ':' by itself means to take entire axis.  

array([[1, 2],
       [4, 5],
       [7, 8]])

In [0]:
A[:2,1:]=0
A

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Transposing arrays and swapping axes

In [0]:
arr=np.random.randn(2,4)#np.random.randn() returns to a maxtix with specified shape, each element is 
#random number from standard normal distribution N(0,1). 
arr

array([[-1.00636069,  0.72807051,  0.49342933, -1.15461629],
       [ 1.49388338,  0.36216412,  0.66747094, -1.51994783]])

In [0]:
arr.T

array([[-1.00636069,  1.49388338],
       [ 0.72807051,  0.36216412],
       [ 0.49342933,  0.66747094],
       [-1.15461629, -1.51994783]])

In [0]:
arr=np.arange(24).reshape(2,3,4)#create a np array with three axes, axis 0 size is 2, axis 1 size is 3, axis 2 size is 4. 
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
arr.swapaxes(1,2)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [0]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

# Universal Functions
Element-wise  array functions. 

In [0]:
arr=np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
x=np.random.randn(8)
x

array([-0.85697016, -0.45721986,  0.18518175,  0.10018212,  1.04870185,
       -0.92766727,  1.19642874, -0.57712509])

In [0]:
y=np.random.rand(8)
y

array([0.07719763, 0.27779   , 0.10146033, 0.36077451, 0.6449896 ,
       0.01031675, 0.35751994, 0.10229626])

In [0]:
x+y

array([-0.77977253, -0.17942985,  0.28664208,  0.46095662,  1.69369146,
       -0.91735052,  1.55394868, -0.47482882])

In [0]:
np.add(x,y)

array([-0.77977253, -0.17942985,  0.28664208,  0.46095662,  1.69369146,
       -0.91735052,  1.55394868, -0.47482882])

In [0]:
np.maximum(x,y)

array([0.07719763, 0.27779   , 0.18518175, 0.36077451, 1.04870185,
       0.01031675, 1.19642874, 0.10229626])

# Conditional Logic on Array Operations

In [0]:
x=np.random.randn(4,4)
y=np.random.randn(4,4)
x,y

(array([[-0.83644872, -0.07377727,  0.57165423,  0.53086547],
        [-2.21843363, -0.5089457 ,  0.76903316, -0.68381539],
        [ 2.4419642 ,  0.0247511 ,  1.06842353,  1.59915281],
        [ 0.60469047, -0.83216659,  1.78823473,  0.77705405]]),
 array([[ 1.35043869, -0.13321215, -0.62885649, -0.31341872],
        [-0.82321778,  0.01811747,  1.54093962,  0.2694529 ],
        [ 1.32632271,  0.35809882, -0.26150461, -0.03885097],
        [-1.65041817,  0.1512174 , -0.53208157,  0.75966116]]))

In [0]:
#np.where(p1, p2, p3) : p1 is the condition, if ture it will return p2, else it will return p3. 
# p1 is usually a boolean arrays. p2 and p3 can be arrays with same shape or scalars.
result=np.where(x>y,x,y)
result

array([[ 1.35043869, -0.07377727,  0.57165423,  0.53086547],
       [-0.82321778,  0.01811747,  1.54093962,  0.2694529 ],
       [ 2.4419642 ,  0.35809882,  1.06842353,  1.59915281],
       [ 0.60469047,  0.1512174 ,  1.78823473,  0.77705405]])

In [0]:
np.where(x>0,x,2)#set only the non-positive value to be 2.

array([[2.        , 2.        , 0.57165423, 0.53086547],
       [2.        , 2.        , 0.76903316, 2.        ],
       [2.4419642 , 0.0247511 , 1.06842353, 1.59915281],
       [0.60469047, 2.        , 1.78823473, 0.77705405]])

# Mathematical and Stantistical Methohds

In [0]:
a=np.random.randn(5,3)
a

array([[-1.09079534, -0.9090807 ,  1.3832155 ],
       [-0.0982891 , -0.05440338,  1.24474082],
       [ 2.68700135,  0.70703182, -1.40187733],
       [ 0.97876954, -0.82357229,  1.280057  ],
       [ 0.33316111, -0.13106114, -0.8282534 ]])

In [0]:
a.mean(1)#compute the mean over columns. its the same as a.mean(axis=1)

array([-0.20555351,  0.36401611,  0.66405195,  0.47841808, -0.20871781])

In [0]:
a.sum(0)#compute the sum over rows. its the same as a.sum(axis=0). 

array([ 2.80984757, -1.21108569,  1.67788259])

In [0]:
a.sum()

3.276644474932275

In [0]:
a.mean()

0.218442964995485

In [0]:
a.argmin()#returns to indices of minimum element. 

8

In [0]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
b.cumsum(0)#across rows, cumulative sum of elements starting from index 0.  

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [0]:
b.cumprod(1)#across columns, cumulative product of element strting from index 1. 

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [0]:
c=np.random.randn(2,3)
c

array([[-0.51352792, -0.03172535,  0.10906999],
       [-0.09153673,  0.98713601,  0.19105015]])

In [0]:
c. sort()#this returns to a sorted copy. a will be different after applying this method.
#without specifying the axis number, it will sort across column.
c

array([[-0.51352792, -0.03172535,  0.10906999],
       [-0.09153673,  0.19105015,  0.98713601]])

In [0]:
c.sort(0) #sort across rows. 
c

array([[-0.51352792, -0.03172535,  0.10906999],
       [-0.09153673,  0.19105015,  0.98713601]])

# Exercise
Please generate a random numpy array of size 200 from standard normal distribution. Then please find the 5% quantile?

# Example
Random Walk

Let's consider a simple random walk strating from 0 with steps of 1 and -1 occuring with equal probability. Then we implement a single random walk with 100 steps using the built-in random module in (i) pure Python and (ii) Numpy. 

Preknowledge:

1. matplotlib is a package in Python for data visualization. 

2. matplotlib.pyplot provides MATLAB-like plotting framework. It is a state-based interface to matplotlib. 

3. numpy.random.randint(low, high, size)
   
   returns to size-shaped numpy array of random integer from low (inclusive) to high (exclusive). size : int or tuple of ints, optional
   
   size defines the shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

In [0]:
#(i) pure Python way to implement random walk.Would you please complete youself?
import random
conda install -c  conda-forge/label/rc matplotlib
import matplotlib.pyplot as plt
position =0
walk=[]
steps=100
#we need a for loop to complete walk list. 




plt.plot(walk)

SyntaxError: invalid syntax (<ipython-input-30-63c5e335667f>, line 3)

In [0]:
# (ii) Use NumPy for random walk. this walk is the cumulative sum of the random steps. Each step is a random draw from  1 and -1. 
import numpy as np
import matplotlib.pyplot as plt
nsteps=100
draws=np.random.randint(0,2,size=nsteps) #draw is a np array with either 0 or 1 as the value of each element. 
steps=np.where(draws>0,1,-1)#steps is a np array with eith 1 or -1 as the value of each element. From draws,if element is 1(>0),the statement is ture, then it will be 1.
walk=steps.cumsum()
plt.plot(walk)

ImportError: No module named matplotlib.pyplot

In [0]:
#Another random fuction. 
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html
np.random.choice(['red', 'pink', 'blue'], size=10, p=[0.5, 0.2, 0.3])

array(['blue', 'red', 'red', 'red', 'pink', 'red', 'pink', 'blue', 'red',
       'blue'], dtype='|S4')